service: serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

resources:
  Resources:
    MyDemoAPI:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyDemoAPI
        Description: This is my API for demonstration purposes

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb

    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyDemoAPI
        Description: This is my API for demonstration purposes
