name: Deploy Lambda 

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: AWS Lambda Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the application
        run:  npm i
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r ./bundle.zip ./
        working-directory: ./
      - name: AWS Lambda Deploy
        if: github.ref == 'refs/heads/development'
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # //  aws_region: ${{ secrets.AWS_REGION }}
        #  //  function_name: 	sam-register-advertiser-dev

          zip_file: ./authService/register-advertiser/bundle.zip
  